// ── Google Drive config ──────────────────────────────────────────────
// Fill these in once.
// 1. Create an API key in Google Cloud Console, enable the Drive API,
//    restrict the key to Drive API (+ HTTP referrer = your domain).
// 2. Create one folder in Drive named e.g. "plantImage", share it as
//    "Anyone with the link — Viewer", copy its folder ID from the URL.
// 3. Upload images into that single folder, named like:
//    malus_domestica_gala_1.jpg, malus_domestica_gala_2.jpg, ...
//    i.e. normalizeName(LatinName + "_" + Name_Variety) + "_" + running number
// 4. Output:
//    [{mimeType=image/jpeg, name=malus_domestica_species_voros.jpg, url=https://drive.google.com/thumbnail?id=17xBWb2t6jgButmxc8va53P_ozyOcSxqh&sz=w1000, id=17xBWb2t6jgButmxc8va53P_ozyOcSxqh}, 
//     {mimeType=image/jpeg, name=malus_domestica_species.jpg, url=https://drive.google.com/thumbnail?id=1FoX7P9LbOyr-qZ73h_0dZWgUttPHcCPw&sz=w1000, id=1FoX7P9LbOyr-qZ73h_0dZWgUttPHcCPw}]
//

const APPS_SCRIPT_URL ='https://script.google.com/macros/s/AKfycbxxwaaITsAj_KN-d5RPZFBlfjLPtAA9f7Vwar7xTHPac4o_GXQEE_woiiv8E0V3q4Ok/exec';
// State
let _carouselImages  = [];   // [{src, name}]
let _carouselIndex   = 0;

function driveImageUrl(fileId, size = 'w1000') {
  return `https://drive.google.com/thumbnail?id=${fileId}&sz=${size}`;
}


export async function loadPlantImage(plantLatinName, plantVariety) {

  // ----------------------------------------------------------
  // Build search name
  // ----------------------------------------------------------

  const searchLatin =
    (plantLatinName || '')
      .trim()
      .replace(/\s+/g, '_');
  console.log('plantLatinName: ',plantLatinName);
  console.log('searchLatin: ',searchLatin);

  const searchVariety =
    (plantVariety || '')
      .trim()
      .replace(/\s+/g, '_');
  console.log('plantVariety: ',plantVariety);
  console.log('searchVariety: ',searchVariety);

  const imgText =
    `${searchLatin}_${searchVariety}`;
  console.log('imgText: ',imgText);

  const searchId =
    normalizeName(imgText);
   console.log('searchId: ',searchId);

  console.log(
    'Search image:',
    searchId
  );


  // Reset carousel

  _carouselImages = [];

  _carouselIndex = 0;

      // Try keys in priority order:
    //   a) numeric Plant_ID (matches files named {Plant_ID}_*.jpg generated by generateImagesJson.js)
    //   b) latin_variety   (e.g. "malus_domestica_species")
    //   c) latin only      (e.g. "malus_domestica" — legacy hand-crafted images.json entries)
  // ----------------------------------------------------------
  // 1. Google Drive via Apps Script
  // ----------------------------------------------------------

  try {

    const url =
      `${APPS_SCRIPT_URL}?search=${encodeURIComponent(searchId)}`;


    console.log(
      'Requesting:',
      url
    );


    const response =
      await fetch(url);


    if (!response.ok) {

      throw new Error(
        `Apps Script request failed: ${response.status}`
      );

    }


    const data =
      await response.json();


    if (
      data.success &&
      data.images &&
      data.images.length
    ) {

      _carouselImages =
        data.images.map(file => ({

          src: file.url,

          name: extractImageName(file.name)

        }));

      console.log('_carouselImages: ',_carouselImages);
      console.log(
        `Found ${_carouselImages.length} Drive image(s)`
      );
      return (_carouselImages);
    }


    console.log(
      'No Google Drive images found'
    );


  } catch (error) {

    console.warn(
      'Google Drive lookup failed:',
      error
    );

  }

  // ----------------------------------------------------------
  // 2. Wikipedia fallback
  // ----------------------------------------------------------

  try {

    const wikiResponse =
      await fetch(
        `https://en.wikipedia.org/api/rest_v1/page/summary/${encodeURIComponent(searchLatin)}`
      );


    if (!wikiResponse.ok) {

      throw new Error(
        'Wikipedia request failed'
      );

    }


    const wikiData =
      await wikiResponse.json();


    const src =
      wikiData.thumbnail?.source ||
      wikiData.originalimage?.source ||
      null;


    if (src) {

      _carouselImages = [

        {
          src: src,

          name: extractImageName(src)
        }

      ];
      return (_carouselImages);
    }


  } catch (error) {

    console.warn(
      'Wikipedia image lookup failed:',
      error
    );

  }


  // ----------------------------------------------------------
  // 3. Default image
  // ----------------------------------------------------------

  _carouselImages = [

    {
      src: 'images/image_default.jpeg',
       //src: 'images/default.jpg',
      name: 'Default image'
    }

  ];
  return (_carouselImages);
}

/**
 * Load a single plant's full row data AND all its Name_Variety values
 * in a single network request.
 *
 * @param1 {string} plantLatinName - The LatinName value to match.
 * @param2 {string} plantVariety - The Name_Variety value to match
 * @returns {{ url: images url}}
 */

function normalizeName(value) {

  return String(value || '')
    .toLowerCase()
    .replace(/\.[^/.]+$/, '')
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '');

}

// Extract a clean display name from a filename or URL
function extractImageName(src) {
  try {
    // Get last path segment, strip extension and underscores
    const seg1 = decodeURIComponent(src.split('/').pop().split('?')[0]);
    console.log('name seg1: ',seg1);
    const seg2 = seg1.replace(/\.[^.]+$/, '').replace(/_/g, ' ');
    console.log('name seg2: ',seg2);
    const seg3 = normalizeName(seg2);  
    console.log('name seg3: ',seg3);
    return seg3;
  } catch {
    return src;
  }
}
